# Generated by Django 5.2.6 on 2025-10-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_homeaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='card_no',
        ),
        migrations.AddField(
            model_name='account',
            name='card_no_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='cvv_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]