# Generated by Django 5.2.6 on 2025-10-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_card_no_account_card_no_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_no_encrypted',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv_encrypted',
            field=models.BinaryField(),
        ),
    ]