# Generated by Django 5.2.6 on 2025-11-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_card_no_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
