# Generated by Django 5.2.6 on 2025-11-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_billingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_no_encrypted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv_encrypted',
            field=models.TextField(),
        ),
    ]
