# Generated by Django 5.2.6 on 2025-11-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
