# Generated by Django 5.2.6 on 2025-11-14 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_tickettype_ticket_ticket_type'),
        ('movie', '0002_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.seat'),
        ),
    ]
