# Generated by Django 5.2.6 on 2025-11-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_ticket_seat'),
        ('movie', '0003_alter_movieshow_auditorium_alter_seat_auditorium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('HELD', 'Held'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='HELD', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movie.movieshow'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='movie.seat'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seat', 'booking')},
        ),
    ]
