# Generated by Django 5.2.6 on 2025-09-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('showtimes', models.JSONField(default=list)),
                ('poster', models.CharField(max_length=200)),
                ('trailer', models.URLField()),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
