# Generated by Django 5.2.6 on 2025-12-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='auditorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movie.auditorium'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='auditorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie.auditorium'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('auditorium', 'row_number', 'seat_number')},
        ),
    ]
